### ISSUE TITLE
Ordering the Board on PCBWay

### ISSUE THREAD

**Issue by Luro02** [yifanlu/psvsd#3]
I am new to ordering PCB's or even assembling them. I want to upgrade my PSVita with the Psvsd Board but sadly it's sold out on Indiegogo :(
I asked you already on Twitter where I can order the Board assembled and you told me to look on PCBWay but sadly I have no clue what to fill in or how to produce the Board. Can you give me a Screennshot of what you filled in ? / share the Project via Link if possible ? ([example](https://www.pcbway.com/project/shareproject/SD2VITA___Gadorach.html))

**Comment by yifanlu** [comment]
1. Download both files from https://github.com/yifanlu/psvsd/releases/tag/v2.1.1
2. Go here https://www.pcbway.com/pcb-assembly.html "Quantity" (I recommend > 100 or it'll be REALLY expensive per unit) "Number of Unique Parts" = 11 "Number of SMT Parts" = 11 "Number of Thru-Holes Parts" = 0. Click calculate.
3. Now change "Assembly Side(s)" to Double sides. Click "PCB Specifications".
4. Change Quantity to the same quantity specified earlier. "Size (single)" = 30x33.2mm "Thickness" = 1.0 and leave other options as is (unless you want to change the silkscreen color).
5. Press calculate and add to cart. You will be asked to upload gerbers for the PCB (pass psvsd-v21-1.zip as is) and to upload the BOM (extract psvsd-v21-1-assembly.zip and pass in the xlsx).
6. Wait a day for them to send you the proper quote. Make sure to tell them to ensure that the GL823 part is the 3.3V version! This is important, they almost messed up the first time.
7. Once you paid and they start assembling, they'll ask for some other files (place and route, assembly instruction, etc). Give them the psvsd-v21-1-assembly.zip

It will cost ~$1400 for 500 pieces. ~$700 for 100 pieces. ~$100 for 10 pieces and so on so it's cheaper to buy more at once.

**Comment by Luro02** [comment]
thanks for the Answer but for a normal Person it's way too expensive (the assemblie) :(
