### ISSUE TITLE
Ordering small run.

### ISSUE THREAD

**Issue by DasKatzchen** [yifanlu/psvsd#4]
If I'm ordering boards for myself, do you think hasl is good enough or do I need to spring for the enig? Also, does the pad on u1 need to be connected or can I cheat by soldering around the edges? Or is it one of the qfn chips that don't have accessible edges?

**Comment by yifanlu** [comment]
1) HASL is good enough
2) It's QFN (no edges)
3) Make sure you get the 3.3V version (the 5V version is called GL823B but is also labeled GL823 on the chip)

**Comment by DasKatzchen** [comment]
Gotcha. Ended up buying it on aliexpress in the end, but this is all useful info to have. It should probably be mentioned somewhere that the board should be 1mm thick. Found that info on my own.
