### ISSUE TITLE
Selling of PSVSD v2.1

### ISSUE THREAD

**Issue by Spheresolid** [yifanlu/psvsd#5]
Hello yifanlu,

I've produced a batch of PSVSD, and I am currently selling them at the suggested price. I wanted to thank you for your time and efforts. I intend on keeping it at a low cost. Please check out my website, where they're available. If you'd like one of mine, please don't hesitate to ask. Thanks again!
http://spheresolid.com/

**Comment by yifanlu** [comment]
Nice! I'll update the site when I see a dozen or so positive reviews.

**Comment by Spheresolid** [comment]
Excellent! Thank you Yifan!
