### ISSUE TITLE
Selling 2 original molecule psvsd's v2.1 (unopened)

### ISSUE THREAD

**Issue by ushilives** [yifanlu/psvsd#6]
Hi there,

Like title states i am selling my psvsd's because i ended up with a slim ps vita and using an micro sd card adapter. Not sure what to sell them for but any interested then please contact me.

Thanks,

Neal

**Comment by yifanlu** [comment]
Sorry, the site only lists resellers not individual sales.

**Comment by ushilives** [comment]
Ok no problem. I'll try eBay or a gaming wesbite.
